/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Ferrari Design System
        'rosso-corsa': '#FF1E00',
        'rosso-corsa-dark': '#CC0000',
        'ferrari-gold': '#FFB800',
        'ferrari-gold-light': '#FFD700',
        'nero': '#0A0A0F',
        'carbon-black': '#0F0F14',
        'surface-elevated': '#16161E',
        'surface-inner': '#1E1E28',
        'surface-highlight': '#2A2A38',
        'border-subtle': '#2D2D3D',
        'border-gold': 'rgba(255, 184, 0, 0.35)',
        'text-primary': '#F0F0F5',
        'text-secondary': '#8B8BA0',
        'text-ghost': '#55556B',
        'soft-red': '#E8103A',
        'medium-yellow': '#FFD300',
        'hard-white': '#F5F5F5',
        'inter-blue': '#0057B7',
        'wet-dark': '#004E8C',
        'success-green': '#00D084',
        'alert-red': '#FF2D2D',
        'mercedes-teal': '#00F5D4',
        'red-bull-blue': '#0033A0',
        'mclaren-orange': '#FF8700',
        'williams-blue': '#00A0DE',
        'aston-green': '#006F62',
      },
      fontFamily: {
        geist: ['Geist', 'system-ui', 'sans-serif'],
        mono: ['Geist Mono', 'monospace'],
      },
      spacing: {
        'page': '48px',
        'section': '32px',
        'card': '24px',
        'element': '16px',
        'tight': '8px',
        'micro': '4px',
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'card': '0 2px 8px rgba(0,0,0,0.3)',
        'card-hover': '0 0 12px rgba(255,184,0,0.08)',
        'gold-glow': '0 0 24px rgba(255,30,0,0.2)',
        'btn-red': '0 4px 16px rgba(255,30,0,0.3)',
        'btn-red-hover': '0 12px 40px rgba(255,30,0,0.45), 0 0 80px rgba(255,30,0,0.15)',
        'btn-green': '0 4px 16px rgba(0,208,132,0.25)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "shimmer": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 4px 24px rgba(255,30,0,0.4)" },
          "50%": { boxShadow: "0 4px 40px rgba(255,30,0,0.6)" },
        },
        "number-tick": {
          "0%": { transform: "translateY(100%)", filter: "blur(4px)" },
          "100%": { transform: "translateY(0)", filter: "blur(0px)" },
        },
        "bounce-subtle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(8px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "shimmer": "shimmer 2s infinite",
        "shimmer-fast": "shimmer 1.5s infinite",
        "pulse-glow": "pulse-glow 1.5s infinite",
        "number-tick": "number-tick 0.3s ease-out",
        "bounce-subtle": "bounce-subtle 2s ease-in-out infinite",
      },
      backgroundImage: {
        'hero-carbon': 'linear-gradient(135deg, #0A0A0F 0%, #141420 50%, #0A0A0F 100%)',
        'gold-shimmer': 'linear-gradient(90deg, transparent 0%, rgba(255,184,0,0.12) 50%, transparent 100%)',
        'red-flare': 'radial-gradient(ellipse at 30% 0%, rgba(255,30,0,0.12) 0%, transparent 60%)',
        'card-bg': 'linear-gradient(160deg, #16161E 0%, #13131A 100%)',
        'pit-panel': 'linear-gradient(180deg, #1E1E28 0%, #181822 100%)',
        'danger-pulse': 'linear-gradient(135deg, #CC0000 0%, #FF1E00 50%, #CC0000 100%)',
        'success-pulse': 'linear-gradient(135deg, #00A060 0%, #00D084 50%, #00A060 100%)',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
