"""
F1 Race Simulation Engine Module

The core orchestration module that integrates physics, weather, AI opponents,
and event management into a complete race simulation. Handles lap-by-lap
advancement, pit stops, overtaking, incidents, safety cars, and strategy
message generation.
"""

import math
import random
from copy import deepcopy
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from .tracks import Track, get_track
from .physics import CarPhysics, BlendedLapTimeEngine, TIRE_COMPOUNDS
from .weather import WeatherState, WeatherSystem
from .ai_opponents import (
    Driver, AIOpponentController, DRIVER_DATABASE, TEAM_BASE_PACE,
)
from .events import (
    RaceEventBus, RaceEvent, SafetyCarController, FlagState, Incident,
)

try:
    from ml.predict import predictor as _ml_predictor
except Exception:
    _ml_predictor = None


# =============================================================================
# DATA CLASSES
# =============================================================================

@dataclass
class TireState:
    """
    State of a car's current tire set.

    Attributes:
        compound: Tire compound name (SOFT, MEDIUM, HARD, INTERMEDIATE, WET).
        age: Number of laps completed on this tire set.
        wear: Wear percentage from 0.0 (new) to 1.0 (completely worn).
    """
    compound: str = "MEDIUM"
    age: int = 0
    wear: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        """Serialize tire state to a dictionary."""
        return {"compound": self.compound, "age": self.age, "wear": self.wear}


@dataclass
class CarState:
    """
    Complete state of a single race car on the track.

    Attributes:
        driver: The Driver controlling this car.
        position: Current race position (1 = leader).
        tire: TireState for the current tire set.
        fuel: Remaining fuel in kilograms.
        lap_time: Last completed lap time in seconds.
        total_time: Cumulative race time in seconds.
        pits: Number of pit stops completed.
        gap_to_leader: Time gap to race leader in seconds (None for leader).
        gap_to_next: Time gap to car ahead in seconds (None for leader).
        drs_available: Whether DRS is available on the next lap.
        ers_mode: Current ERS deployment mode.
        ers_battery: ERS battery level as percentage (0-100).
        finished: Whether the car has completed the race.
        alive: Whether the car is still in the race (not DNF).
        track_fraction: Position on circuit (0.0–1.0) for track map.
        track_limit_violations: Running count of track limit warnings this race.
        contact_penalties: Running count of contact time penalties this race.
    """
    driver: Driver
    position: int = 1
    tire: TireState = field(default_factory=lambda: TireState("MEDIUM", 0, 0.0))
    fuel: float = 100.0
    lap_time: float = 0.0
    total_time: float = 0.0
    pits: int = 0
    gap_to_leader: Optional[float] = None
    gap_to_next: Optional[float] = None
    drs_available: bool = False
    ers_mode: str = "BALANCED"
    ers_battery: float = 100.0
    finished: bool = False
    alive: bool = True
    track_fraction: float = 0.0       # 0.0 = start/finish, goes forward
    track_limit_violations: int = 0   # cumulative track limits count
    contact_penalties: int = 0        # cumulative contact penalty count
    pending_time_penalty: float = 0.0 # seconds to add at next pit stop (stewarding decision)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize car state to a dictionary."""
        return {
            "driver": {
                "name": self.driver.name,
                "team": self.driver.team,
                "number": self.driver.number,
            },
            "position": self.position,
            "tire": self.tire.to_dict(),
            "fuel": round(self.fuel, 2),
            "lap_time": round(self.lap_time, 3),
            "total_time": round(self.total_time, 3),
            "pits": self.pits,
            "gap_to_leader": round(self.gap_to_leader, 3) if self.gap_to_leader is not None else None,
            "gap_to_next": round(self.gap_to_next, 3) if self.gap_to_next is not None else None,
            "drs_available": self.drs_available,
            "ers_mode": self.ers_mode,
            "ers_battery": round(self.ers_battery, 1),
            "finished": self.finished,
            "alive": self.alive,
            "track_fraction": round(self.track_fraction, 4),
            "track_limit_violations": self.track_limit_violations,
            "contact_penalties": self.contact_penalties,
            "pending_time_penalty": round(self.pending_time_penalty, 1),
        }


@dataclass
class StrategyMessage:
    """
    Strategy advisory message generated by the race engineer.

    Attributes:
        msg_type: Message urgency level (URGENT, WARNING, INFO, OPPORTUNITY).
        text: Human-readable message content.
        confidence: Confidence level of the recommendation (0.0 to 1.0).
        trigger_lap: Lap number when the message was generated.
    """
    msg_type: str  # "URGENT", "WARNING", "INFO", "OPPORTUNITY"
    text: str
    confidence: float
    trigger_lap: int

    def to_dict(self) -> Dict[str, Any]:
        """Serialize strategy message to a dictionary."""
        return {
            "type": self.msg_type,
            "text": self.text,
            "confidence": round(self.confidence, 2),
            "trigger_lap": self.trigger_lap,
        }


@dataclass
class RaceState:
    """
    Complete snapshot of the race at a specific moment.

    Attributes:
        lap: Current lap number (0 = pre-race).
        total_laps: Total number of laps in the race.
        status: Race status string ("WAITING", "RUNNING", "FINISHED", "ABORTED").
        leaderboard: Ordered list of CarState objects (leader first).
        player: CarState of the human player.
        weather: Current WeatherState.
        messages: List of recent StrategyMessage objects.
        flag: Current FlagState.
        incidents: List of active Incident objects.
        events_log: List of recent RaceEvent objects.
    """
    lap: int = 0
    total_laps: int = 0
    status: str = "WAITING"
    leaderboard: List[CarState] = field(default_factory=list)
    player: Optional[CarState] = None
    weather: Optional[WeatherState] = None
    messages: List[StrategyMessage] = field(default_factory=list)
    flag: FlagState = FlagState.GREEN
    incidents: List[Dict[str, Any]] = field(default_factory=list)
    events_log: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize race state to a dictionary."""
        weather_dict = None
        if self.weather:
            weather_dict = {
                "condition": self.weather.condition,
                "air_temp": self.weather.air_temp,
                "track_temp": self.weather.track_temp,
                "rain_intensity": self.weather.rain_intensity,
                "track_dampness": self.weather.track_dampness,
                "wind_speed": getattr(self.weather, "wind_speed", 0.0),
                # Frontend compatibility aliases
                "rain_probability": self.weather.rain_intensity,
                "is_raining": self.weather.rain_intensity > 0.05,
            }

        messages_list = [m.to_dict() for m in self.messages]

        return {
            "lap": self.lap,
            "total_laps": self.total_laps,
            "status": self.status,
            "leaderboard": [c.to_dict() for c in self.leaderboard],
            "player": self.player.to_dict() if self.player else None,
            "weather": weather_dict,
            "messages": messages_list,
            "flag": self.flag.name,
            "incidents": self.incidents,
            "events_log": [e.to_dict() if hasattr(e, 'to_dict') else e for e in self.events_log[-15:]],
            # Frontend compatibility aliases
            "current_lap": self.lap,
            "strategy_messages": messages_list,
        }


# =============================================================================
# RACE ENGINE
# =============================================================================

class RaceEngine:
    """
    Central orchestrator for the F1 race simulation.

    Manages the complete race lifecycle from initialization through each lap
    to the finish. Integrates physics calculations, weather progression,
    AI opponent decisions, incident generation, safety car deployments,
    and strategy message generation.
    """

    # ERS battery recharge per lap under normal conditions
    ERS_RECHARGE_PER_LAP: float = 12.0
    # Maximum ERS battery capacity
    ERS_MAX_BATTERY: float = 100.0
    # DRS activation gap threshold (seconds within car ahead)
    DRS_GAP_THRESHOLD: float = 1.0
    # Fuel consumption safety margin (extra fuel carried)
    FUEL_SAFETY_MARGIN: float = 3.0

    def __init__(
        self,
        track: Track,
        player_team: str,
        starting_compound: str = "MEDIUM",
        air_temp: float = 25.0,
        air_temperature: Optional[float] = None,  # alias accepted from router
        race_month: int = 7,
        random_seed: Optional[int] = None,
        player_driver: Optional[int] = None,
    ) -> None:
        """
        Initialize the race engine.

        Args:
            track: The Track object for this race.
            player_team: Name of the player's constructor team.
            starting_compound: Starting tire compound (SOFT, MEDIUM, HARD).
            air_temp: Starting air temperature in Celsius.
            air_temperature: Alias for air_temp (accepted from API layer).
            race_month: Month of the race (1-12) for weather patterns.
            random_seed: Optional seed for reproducible race outcomes.
            player_driver: Driver number for the player (None = team's first driver).
        """
        self.track = track
        self.player_team = player_team
        self.starting_compound = starting_compound
        self.air_temp = air_temperature if air_temperature is not None else air_temp
        self.race_month = race_month
        self.player_driver_number = player_driver
        self._seed = random_seed
        self._rng = random.Random(random_seed)

        # Subsystems
        self._weather_system = WeatherSystem(track, race_month, random_seed)
        self._event_bus = RaceEventBus()
        self._sc_controller = SafetyCarController(random_seed)

        # Race state
        self._state: RaceState = RaceState()
        self._cars: List[CarState] = []
        self._player_car: Optional[CarState] = None
        self._physics_engines: Dict[int, Any] = {}  # BlendedLapTimeEngine or CarPhysics
        self._ai_controller: Optional[AIOpponentController] = None
        self._current_lap: int = 0
        self._race_finished: bool = False
        # Tracks the last lap on which a given (attacker_number, defender_number) pair overtook.
        # Prevents the same two cars from trading places every single lap.
        self._overtake_cooldown: Dict[Tuple[int, int], int] = {}

    # -------------------------------------------------------------------------
    # RACE LIFECYCLE
    # -------------------------------------------------------------------------

    def _simulate_qualifying(self) -> List[Driver]:
        """
        Run a simplified Q1/Q2/Q3 knockout qualifying session.

        Each driver sets a simulated qualifying lap:
            time = TEAM_BASE_PACE + skill_modifier + noise
        where skill_modifier gives top drivers up to ~2 s advantage and noise
        is tight (sigma=0.06 s) as qualifying is more controlled than race pace.

        Q1: all 20, bottom 5 eliminated (P16-P20).
        Q2: top 15, bottom 5 eliminated (P11-P15).
        Q3: top 10 set final grid (P1-P10).

        Returns:
            Drivers in qualifying order (index 0 = pole).
        """
        all_drivers = list(DRIVER_DATABASE.values())
        q_times: Dict[int, float] = {}
        for driver in all_drivers:
            base = TEAM_BASE_PACE.get(driver.team, 90.0)
            # Best drivers gain up to ~2 s vs weakest; sigma 0.06 s = qualifying precision
            skill_mod = -(driver.skill - 0.85) * 2.5
            noise = self._rng.gauss(0.0, 0.06)
            q_times[driver.number] = base + skill_mod + noise

        sorted_all = sorted(all_drivers, key=lambda d: q_times[d.number])

        # Q1 elimination: bottom 5 keep their Q1 positions but don't improve
        q2_field = sorted_all[:15]
        q1_eliminated = sorted_all[15:]  # P16-P20

        # Q2 elimination
        q3_field = sorted_all[:10]
        q2_eliminated = sorted_all[10:15]  # P11-P15

        # Assign grid: Q3 first (fastest to slowest), then Q2 elim, then Q1 elim
        grid = q3_field + q2_eliminated + q1_eliminated
        return grid

    def _ai_starting_compound(self, qualifying_pos: int) -> str:
        """
        Choose a strategically sensible starting compound for an AI car.

        High-abrasion tracks (severity ≥ 7): MEDIUM or HARD starts dominate.
        Medium abrasion (4-6): front runners often gamble SOFT, midfield MEDIUM.
        Low abrasion (< 4): SOFT viable across the grid.
        """
        severity = self.track.tire_severity

        if severity >= 7:
            if qualifying_pos <= 5:
                return "MEDIUM"
            return "HARD"
        elif severity >= 4:
            if qualifying_pos <= 5:
                # Front runners: aggressive SOFT for early lead, plan early pit
                return self._rng.choice(["SOFT", "SOFT", "MEDIUM"])
            elif qualifying_pos <= 15:
                return "MEDIUM"
            else:
                return self._rng.choice(["MEDIUM", "HARD"])
        else:
            # Low severity — SOFT viable across grid
            if qualifying_pos <= 10:
                return "SOFT"
            elif qualifying_pos <= 16:
                return "MEDIUM"
            return "HARD"

    def start_race(self) -> RaceState:
        """
        Initialize and start the race.

        Runs a qualifying simulation to determine grid positions, then
        creates all 20 cars with strategically chosen starting compounds,
        and wires up BlendedLapTimeEngine instances (ML + physics) for
        each driver.

        Returns:
            Initial RaceState after race start.
        """
        # Initialize weather
        weather = self._weather_system.initialize()

        # Qualifying simulation → realistic grid order
        grid_drivers = self._simulate_qualifying()

        # Resolve track name for ML predictor
        track_name = getattr(self.track, "name", "default").lower().replace(" ", "_")

        # Create car states
        self._cars = []
        for pos, driver in enumerate(grid_drivers, 1):
            if self.player_driver_number is not None:
                is_player = (driver.number == self.player_driver_number)
            else:
                is_player = (driver.team == self.player_team)

            if is_player:
                compound = self.starting_compound
            else:
                compound = self._ai_starting_compound(pos)

            fuel_load = (self.track.fuel_per_lap * self.track.laps) + self.FUEL_SAFETY_MARGIN

            car = CarState(
                driver=driver,
                position=pos,
                tire=TireState(compound=compound, age=0, wear=0.0),
                fuel=fuel_load,
                lap_time=0.0,
                total_time=0.0,
                pits=0,
                gap_to_leader=0.0 if pos == 1 else None,
                gap_to_next=None,
                drs_available=False,
                ers_mode="BALANCED",
                ers_battery=100.0,
                finished=False,
                alive=True,
            )

            self._cars.append(car)

            # Build blended engine: team-specific base pace, ML tire degradation
            base_pace = TEAM_BASE_PACE.get(driver.team, 90.0)
            base_pace -= (driver.skill - 0.85) * 2.0  # top driver ~0.24 s faster than midfield

            car_physics = CarPhysics(
                team=driver.team,
                base_pace=base_pace,
                track=self.track,
                random_seed=self._seed,
            )
            self._physics_engines[driver.number] = BlendedLapTimeEngine(
                car_physics=car_physics,
                predictor=_ml_predictor,
                track_name=track_name,
            )

            if is_player:
                self._player_car = car

        if self._player_car is None:
            self._player_car = self._cars[0]

        # Initialize AI controller
        self._ai_controller = AIOpponentController(
            drivers=[c.driver for c in self._cars if c.driver.team != self.player_team],
            track=self.track,
            random_seed=self._seed,
        )

        # Build initial state
        self._state = RaceState(
            lap=0,
            total_laps=self.track.laps,
            status="RUNNING",
            leaderboard=list(self._cars),
            player=self._player_car,
            weather=weather,
            messages=[],
            flag=FlagState.GREEN,
            incidents=[],
            events_log=[],
        )

        self._current_lap = 0
        self._race_finished = False

        # Initial strategy message
        self._state.messages.append(StrategyMessage(
            msg_type="INFO",
            text=f"Race started at {self.track.name}. Good luck!",
            confidence=1.0,
            trigger_lap=0,
        ))

        return self._state

    def advance_lap(self, actions: Optional[Dict[str, Any]] = None) -> RaceState:
        """
        Advance the race by one lap, processing all simulation steps.

        Execution order:
        1. Update weather conditions
        2. Process player actions (ERS mode, etc.)
        3. Calculate lap times using physics for all cars
        4. Update positions based on lap times
        5. Process AI pit decisions
        6. Check and resolve overtakes
        7. Generate and process incidents
        8. Update safety car status
        9. Update gaps and timing
        10. Consume fuel and recharge ERS
        11. Generate strategy messages
        12. Check race finish

        Args:
            actions: Optional dict of player actions for this lap:
                - ers_mode: ERS mode to set (NONE, BALANCED, ATTACK, DEFEND)
                - pit: True if player wants to pit (use player_pit separately)

        Returns:
            Updated RaceState after the lap.
        """
        if self._race_finished:
            return self._state

        actions = actions or {}
        self._current_lap += 1
        self._state.lap = self._current_lap

        # 1. Update weather
        if self._state.weather:
            self._state.weather = self._weather_system.advance(self._state.weather)

        # 2. Process player actions
        if "ers_mode" in actions and self._player_car:
            self._player_car.ers_mode = actions["ers_mode"]

        # 3. Calculate lap times for all cars
        self._calculate_lap_times()

        # 4. Update positions based on cumulative times
        self._update_positions()

        # 5. Update gaps FIRST so pit decisions and overtakes use fresh gap data
        self._update_gaps()

        # 6. Process AI pit decisions (uses fresh gaps from step 5)
        self._process_ai_pit_decisions()

        # 7. Process overtakes (uses fresh gaps from step 5)
        self._process_overtakes()

        # 8. Check and generate incidents
        self._check_incidents()

        # 9. Update safety car status — emit flag-change events to events_log
        prev_flag = self._state.flag
        self._sc_controller.check_incident(self._state)
        new_flag = self._sc_controller.get_flag_state()
        self._state.flag = new_flag
        self._sc_controller.tick()

        if new_flag != prev_flag:
            if new_flag == FlagState.SAFETY_CAR:
                self._state.events_log.append({
                    "event_type": "safety_car",
                    "lap": self._current_lap,
                    "data": {
                        "laps_remaining": self._sc_controller.sc_laps_remaining,
                        "message": "Safety Car deployed",
                    },
                })
            elif new_flag == FlagState.VSC:
                self._state.events_log.append({
                    "event_type": "virtual_safety_car",
                    "lap": self._current_lap,
                    "data": {"message": "Virtual Safety Car"},
                })
            elif prev_flag in (FlagState.SAFETY_CAR, FlagState.VSC) and new_flag == FlagState.GREEN:
                self._state.events_log.append({
                    "event_type": "green_flag",
                    "lap": self._current_lap,
                    "data": {"message": "Safety Car in — racing resumes"},
                })

        # 10. Re-update gaps after pit stops and overtakes changed total_times
        self._update_gaps()

        # 11. Consume fuel and recharge ERS for all cars
        self._consume_resources()

        # 12. Generate strategy messages
        self._generate_messages()

        # 13. Check race finish
        if self._current_lap >= self.track.laps:
            self._finish_race()

        # Update leaderboard: finished first, then alive by total_time, then DNFs

        alive_cars = [c for c in self._cars if c.alive and not c.finished]
        dnf_cars = [c for c in self._cars if not c.alive]
        finished_cars = [c for c in self._cars if c.finished]

        # Sort alive cars by total time
        alive_cars.sort(key=lambda c: c.total_time)
        # Sort finished cars by total time
        finished_cars.sort(key=lambda c: c.total_time)
        # DNF cars keep their last position

        self._state.leaderboard = finished_cars + alive_cars + dnf_cars
        for i, car in enumerate(self._state.leaderboard, 1):
            car.position = i

        self._state.player = self._player_car

        return self._state

    def player_pit(self, compound: str) -> RaceState:
        """
        Execute a pit stop for the player car.

        Args:
            compound: Tire compound to switch to (SOFT, MEDIUM, HARD, INTERMEDIATE, WET).

        Returns:
            Updated RaceState after the pit stop.
        """
        if self._player_car is None or not self._player_car.alive:
            return self._state

        # Apply pit stop time loss + any pending steward penalties
        pit_time = self.track.pit_loss_time + self._player_car.pending_time_penalty
        self._player_car.total_time += pit_time
        served_penalty = self._player_car.pending_time_penalty
        self._player_car.pending_time_penalty = 0.0

        # Change tires
        self._player_car.tire = TireState(compound=compound, age=0, wear=0.0)
        self._player_car.pits += 1

        # Log event
        event = RaceEvent(
            event_type="pit",
            lap=self._current_lap,
            data={
                "driver": self._player_car.driver.name,
                "driver_number": self._player_car.driver.number,
                "compound": compound,
                "pit_time": round(pit_time, 1),
                "penalty_served": round(served_penalty, 1) if served_penalty > 0 else None,
            },
        )
        self._event_bus.emit(event)
        self._state.events_log.append(event.to_dict())

        # Add message
        penalty_note = f" +{served_penalty:.0f}s steward penalty served." if served_penalty > 0 else ""
        self._state.messages.append(StrategyMessage(
            msg_type="INFO",
            text=f"Pit stop completed. New {compound} tires fitted.{penalty_note}",
            confidence=1.0,
            trigger_lap=self._current_lap,
        ))

        # Recalculate gaps and track positions after the pit penalty
        self._update_positions()
        self._update_gaps()
        self._state.leaderboard = [c for c in sorted(
            [c for c in self._cars if c.alive and not c.finished],
            key=lambda c: c.total_time,
        )] + [c for c in self._cars if c.finished] + [c for c in self._cars if not c.alive]
        for i, car in enumerate(self._state.leaderboard, 1):
            car.position = i
        self._state.player = self._player_car

        return self._state

    def set_ers_mode(self, mode: str) -> RaceState:
        """
        Set the ERS deployment mode for the player car.

        Args:
            mode: ERS mode (NONE, BALANCED, ATTACK, DEFEND).

        Returns:
            Updated RaceState.
        """
        if self._player_car:
            valid_modes = ["NONE", "BALANCED", "ATTACK", "DEFEND"]
            if mode in valid_modes:
                self._player_car.ers_mode = mode
                self._state.messages.append(StrategyMessage(
                    msg_type="INFO",
                    text=f"ERS mode set to {mode}",
                    confidence=1.0,
                    trigger_lap=self._current_lap,
                ))
        return self._state

    def get_state(self) -> RaceState:
        """
        Return the current race state.

        Returns:
            Current RaceState snapshot.
        """
        return self._state

    # -------------------------------------------------------------------------
    # INTERNAL METHODS
    # -------------------------------------------------------------------------

    def _calculate_lap_times(self) -> None:
        """
        Calculate lap times for all cars using the physics engine.

        Each car's lap time is computed based on:
        - Base car pace
        - Tire degradation (three-phase model)
        - Fuel load
        - Weather conditions
        - Track evolution (rubbering-in)
        - DRS usage
        - ERS deployment
        - Traffic gaps
        """
        track_evolution = self._current_lap

        for car in self._cars:
            if not car.alive or car.finished:
                continue

            physics = self._physics_engines.get(car.driver.number)
            if physics is None:
                continue

            # Determine if DRS is used
            drs_used = car.drs_available and self._state.flag == FlagState.GREEN

            # Get traffic gap to car ahead
            traffic_gap = car.gap_to_next

            # Calculate lap time
            lap_time = physics.calculate_lap_time(
                tire_age=car.tire.age,
                compound=car.tire.compound,
                fuel_load=car.fuel,
                weather=self._state.weather,
                track_evolution=track_evolution,
                drs_used=drs_used,
                ers_mode=car.ers_mode,
                traffic_gap=traffic_gap,
            )

            # Apply driver consistency modifier
            # More consistent drivers have less lap time variance
            consistency_bonus = (car.driver.consistency - 0.5) * 0.1
            lap_time -= consistency_bonus

            # Wet weather skill modifier
            if self._state.weather and hasattr(self._state.weather, 'condition'):
                if self._state.weather.condition in ("DRIZZLE", "LIGHT_RAIN", "HEAVY_RAIN"):
                    wet_bonus = (car.driver.wet_skill - 0.5) * 0.8
                    lap_time -= wet_bonus

            # Safety car speed reduction
            if self._state.flag == FlagState.SAFETY_CAR:
                lap_time *= 1.25  # ~25% slower under SC
            elif self._state.flag == FlagState.VSC:
                lap_time *= 1.12  # ~12% slower under VSC

            car.lap_time = max(lap_time, self.track.reference_lap_times.get(car.tire.compound, 90.0) * 0.90)
            car.total_time += car.lap_time
            car.tire.age += 1

            # Tire failure beyond predicted life
            if car.alive and car.tire.compound in ("SOFT", "MEDIUM", "HARD"):
                fail_prob = self._tire_failure_probability(car.tire.compound, car.tire.age)
                if fail_prob > 0 and self._rng.random() < fail_prob:
                    self._handle_tire_failure(car)

            # Track limit violations (real F1: 3 warnings, then 5s penalty from 4th onward)
            if car.alive and not car.finished and self._check_track_limits(car):
                car.track_limit_violations += 1
                n = car.track_limit_violations
                is_player = car.driver.team == self.player_team

                if n <= 3:
                    # First three: warning only (FIA sends a note to the team)
                    self._state.events_log.append({
                        "event_type": "track_limits_warning",
                        "lap": self._current_lap,
                        "data": {"driver": car.driver.name, "violations": n},
                    })
                    if is_player:
                        self._state.messages.append(StrategyMessage(
                            msg_type="WARNING",
                            text=f"Track limits warning {n}/3 — next violation earns a 5s penalty",
                            confidence=1.0, trigger_lap=self._current_lap,
                        ))
                else:
                    # 4th violation onward: 5s time penalty queued for next pit stop
                    car.pending_time_penalty += 5.0
                    self._state.events_log.append({
                        "event_type": "track_limits_penalty",
                        "lap": self._current_lap,
                        "data": {"driver": car.driver.name, "violations": n, "penalty_s": 5},
                    })
                    if is_player:
                        self._state.messages.append(StrategyMessage(
                            msg_type="URGENT",
                            text=f"5s time penalty issued (violation #{n}) — served at next pit stop",
                            confidence=1.0, trigger_lap=self._current_lap,
                        ))

            # Update tire wear
            compound_data = TIRE_COMPOUNDS.get(car.tire.compound)
            if compound_data:
                wear_rate = 1.0 / compound_data.stint_limit
                car.tire.wear = min(1.0, car.tire.wear + wear_rate + self._rng.gauss(0, 0.02))

    def _update_positions(self) -> None:
        """
        Update race positions based on cumulative race times.

        Cars are sorted by total race time, with alive cars ranked above DNF cars.
        """
        # Sort alive cars by total time (leader has lowest total time)
        alive_cars = [c for c in self._cars if c.alive and not c.finished]
        alive_cars.sort(key=lambda c: c.total_time)

        # Update positions
        for i, car in enumerate(alive_cars, 1):
            car.position = i

    def _process_ai_pit_decisions(self) -> None:
        """
        Process pit stop decisions for all AI-controlled cars.

        Each AI driver evaluates whether to pit based on tire age,
        weather conditions, safety car status, and strategic factors.
        """
        if self._ai_controller is None:
            return

        for car in self._cars:
            if not car.alive or car.finished or car.driver.team == self.player_team:
                continue

            decision = self._ai_controller.decide_pit(car.driver, self._state)
            if decision:
                compound = decision.get("compound", "MEDIUM")
                reason = decision.get("reason", "strategic")

                # Execute pit stop — include any pending steward penalties
                pit_time = self.track.pit_loss_time + car.pending_time_penalty
                car.total_time += pit_time
                car.pending_time_penalty = 0.0
                car.tire = TireState(compound=compound, age=0, wear=0.0)
                car.pits += 1

                # Update AI controller's pit tracking
                if self._ai_controller:
                    self._ai_controller._last_pit_lap[car.driver.number] = self._current_lap
                    if "rain" in reason or "wet" in reason or "dry" in reason or "inter" in reason:
                        self._ai_controller._last_weather_pit_lap[car.driver.number] = self._current_lap

                # Log event
                event = RaceEvent(
                    event_type="pit",
                    lap=self._current_lap,
                    data={
                        "driver": car.driver.name,
                        "driver_number": car.driver.number,
                        "compound": compound,
                        "reason": reason,
                    },
                )
                self._event_bus.emit(event)
                self._state.events_log.append(event.to_dict())

    def _process_overtakes(self) -> None:
        """
        Process overtaking attempts between adjacent cars.

        Rules applied to keep results realistic:
        - Attacker must have a genuine lap-time advantage (≥ 0.15 s faster this lap)
        - Same pair may not swap again within 4 laps (cooldown)
        - At most 3 overtakes are resolved per lap across the whole field
        - Overtake bonus is 0.4–0.8 s so the new leader holds position for several laps
        """
        if self._state.flag != FlagState.GREEN:
            return  # No overtaking under SC/VSC/RED

        # Per-lap cap — realistic races rarely see more than 2-3 on-track passes per lap
        MAX_OVERTAKES_PER_LAP = 3
        COOLDOWN_LAPS = 4
        PACE_THRESHOLD = 0.15  # attacker must be this many seconds/lap faster to attempt

        # Get alive cars sorted by total race time (P1 first)
        alive_cars = [c for c in self._cars if c.alive and not c.finished]
        alive_cars.sort(key=lambda c: c.total_time)

        overtakes_this_lap = 0

        for i in range(1, len(alive_cars)):
            if overtakes_this_lap >= MAX_OVERTAKES_PER_LAP:
                break

            attacker = alive_cars[i]
            defender = alive_cars[i - 1]

            # Calculate gap using current total times
            gap = attacker.total_time - defender.total_time

            # Update DRS availability (based on gap regardless of overtake attempt)
            if gap < self.DRS_GAP_THRESHOLD and getattr(self.track, "drs_zones", 0) > 0:
                attacker.drs_available = True
            else:
                attacker.drs_available = False

            # Must be within the overtaking window
            if gap >= 1.2:
                continue

            # Pace check: attacker must be genuinely faster this lap
            pace_delta = defender.lap_time - attacker.lap_time  # positive = attacker faster
            if pace_delta < PACE_THRESHOLD and not attacker.drs_available:
                # No DRS and no meaningful pace advantage → can't overtake
                if gap < 0.4 and self._current_lap > 1:
                    self._check_contact(attacker, defender)
                continue

            # Cooldown: same pair can't fight again too soon
            pair_key = (attacker.driver.number, defender.driver.number)
            last_lap = self._overtake_cooldown.get(pair_key, -999)
            if self._current_lap - last_lap < COOLDOWN_LAPS:
                continue

            # Attempt overtake via AI controller
            if self._ai_controller:
                success = self._ai_controller.attempt_overtake(
                    attacker.driver, defender.driver, self._state
                )

                if success:
                    # Swap: give attacker meaningful gap so they hold position
                    overtake_bonus = 0.4 + self._rng.random() * 0.4  # 0.4–0.8 s
                    attacker.total_time = defender.total_time - overtake_bonus
                    overtakes_this_lap += 1

                    self._overtake_cooldown[pair_key] = self._current_lap
                    # Also prevent immediate revenge from defender
                    self._overtake_cooldown[(defender.driver.number, attacker.driver.number)] = self._current_lap

                    event = RaceEvent(
                        event_type="overtake",
                        lap=self._current_lap,
                        data={
                            "attacker": attacker.driver.name,
                            "attacker_number": attacker.driver.number,
                            "defender": defender.driver.name,
                            "defender_number": defender.driver.number,
                        },
                    )
                    self._event_bus.emit(event)
                    self._state.events_log.append(event.to_dict())
                else:
                    # Failed overtake at close range → possible contact
                    if gap < 0.4 and self._current_lap > 1:
                        self._check_contact(attacker, defender)

    def _check_incidents(self) -> None:
        """
        Generate and process race incidents.

        Incidents are probabilistically generated based on track characteristics,
        weather conditions, and driver aggression. Severe incidents may trigger
        safety car deployments.
        """
        if self._ai_controller is None:
            return

        # Check for new incidents
        incident = self._ai_controller.generate_incident(self._state)

        if incident:
            # Add to state incidents
            self._state.incidents.append(incident)

            # Handle DNF for critical incidents
            if incident.get("severity") == "critical":
                # Find the involved car and mark as DNF
                for car in self._cars:
                    if car.driver.number == incident.get("driver_number"):
                        car.alive = False
                        break

            # Log event
            event = RaceEvent(
                event_type="incident",
                lap=self._current_lap,
                data=incident,
            )
            self._event_bus.emit(event)
            self._state.events_log.append(event.to_dict())

            # Emit sector-specific yellow flag for non-trivial incidents
            severity = incident.get("severity", "minor")
            if severity in ("moderate", "major", "critical"):
                sector = incident.get("sector", self._rng.randint(1, 3))
                self._state.events_log.append({
                    "event_type": "yellow_flag",
                    "lap": self._current_lap,
                    "data": {
                        "sector": sector,
                        "driver": incident.get("driver_name", "?"),
                        "severity": severity,
                    },
                })

            # DNF event for critical incidents
            if severity == "critical":
                self._state.events_log.append({
                    "event_type": "dnf",
                    "lap": self._current_lap,
                    "data": {
                        "driver": incident.get("driver_name", "?"),
                        "reason": incident.get("description", "accident"),
                    },
                })

            # Add message
            severity_msg = {
                "minor": ("INFO", incident.get("description", "")),
                "moderate": ("WARNING", incident.get("description", "")),
                "major": ("URGENT", incident.get("description", "")),
                "critical": ("URGENT", incident.get("description", "")),
            }
            msg_type, msg_text = severity_msg.get(
                incident.get("severity", "minor"), ("INFO", "")
            )

            self._state.messages.append(StrategyMessage(
                msg_type=msg_type,
                text=msg_text,
                confidence=0.9,
                trigger_lap=self._current_lap,
            ))

    def _update_gaps(self) -> None:
        """
        Calculate time gaps between all cars.

        gap_to_leader: Time behind the race leader.
        gap_to_next: Time behind the car immediately ahead.
        """
        # Sort by total time
        sorted_cars = sorted(
            [c for c in self._cars if c.alive],
            key=lambda c: c.total_time,
        )

        if not sorted_cars:
            return

        # Leader has no gaps
        leader = sorted_cars[0]
        leader.gap_to_leader = 0.0
        leader.gap_to_next = None

        # Calculate gaps for all other cars
        for i in range(1, len(sorted_cars)):
            car = sorted_cars[i]
            car_ahead = sorted_cars[i - 1]

            car.gap_to_leader = car.total_time - leader.total_time
            car.gap_to_next = car.total_time - car_ahead.total_time

            # DRS availability: within 1.0s of car ahead AND track has DRS zones
            car.drs_available = (
                car.gap_to_next is not None
                and car.gap_to_next < self.DRS_GAP_THRESHOLD
                and getattr(self.track, "drs_zones", 0) > 0
            )

        # Compute track_fraction for track map.
        # We express position as an absolute value: lap_number + intra_lap_fraction
        # so the frontend animation always moves cars forward by ~1.0 each tick.
        # Leader: fraction = current_lap (integer part stripped by frontend % 1 = 0.0)
        # Others: current_lap minus how many laps they're behind = current_lap - gap/ref
        ref_lap_time = max(
            leader.lap_time if leader.lap_time > 30 else 0,
            self.track.reference_lap_times.get("MEDIUM", 90.0) * 0.88,
        )
        leader.track_fraction = float(self._current_lap % 1000)  # always .0
        for car in sorted_cars[1:]:
            gap = car.gap_to_leader or 0.0
            abs_pos = self._current_lap - (gap / ref_lap_time)
            car.track_fraction = round(abs_pos % 1000, 4)

    def _consume_resources(self) -> None:
        """
        Consume fuel and manage ERS battery for all cars.

        Fuel is consumed per lap based on track-specific consumption rates.
        ERS battery drains based on deployment mode and recharges each lap.
        """
        for car in self._cars:
            if not car.alive or car.finished:
                continue

            # Consume fuel
            fuel_consumed = self.track.fuel_per_lap + self._rng.gauss(0, 0.02)
            car.fuel = max(0.0, car.fuel - fuel_consumed)

            # ERS management
            ers_costs = {"NONE": 0.0, "BALANCED": 8.0, "ATTACK": 18.0, "DEFEND": 14.0}
            ers_drain = ers_costs.get(car.ers_mode, 8.0)
            car.ers_battery = max(0.0, car.ers_battery - ers_drain)
            car.ers_battery = min(self.ERS_MAX_BATTERY,
                                   car.ers_battery + self.ERS_RECHARGE_PER_LAP)

            # Auto-switch ERS if battery depleted
            if car.ers_battery < 5.0:
                car.ers_mode = "NONE"

    def _generate_messages(self) -> None:
        """
        Generate strategy messages based on current race state.

        Messages are triggered by specific conditions:
        - Tire degradation warnings
        - Rain forecasts
        - Undercut threats
        - Safety car opportunities
        - Fuel warnings
        - Track position opportunities
        """
        if self._player_car is None or not self._player_car.alive:
            return

        messages: List[StrategyMessage] = []
        car = self._player_car

        # 1. Tire degradation warning
        tire_age = car.tire.age
        compound = car.tire.compound

        if compound == "SOFT" and tire_age > 12:
            messages.append(StrategyMessage(
                msg_type="WARNING",
                text=f"WARNING: Tire degradation accelerating on SOFTs (lap {tire_age}) — pit window opening",
                confidence=min(0.95, 0.6 + (tire_age - 12) * 0.03),
                trigger_lap=self._current_lap,
            ))
        elif compound == "MEDIUM" and tire_age > 22:
            messages.append(StrategyMessage(
                msg_type="WARNING",
                text=f"WARNING: MEDIUM tires at {tire_age} laps — consider pitting soon",
                confidence=min(0.90, 0.5 + (tire_age - 22) * 0.04),
                trigger_lap=self._current_lap,
            ))
        elif compound == "HARD" and tire_age > 35:
            messages.append(StrategyMessage(
                msg_type="WARNING",
                text=f"INFO: HARD tires at {tire_age} laps — degradation increasing",
                confidence=min(0.85, 0.5 + (tire_age - 35) * 0.03),
                trigger_lap=self._current_lap,
            ))

        # 2. Rain forecast
        if self._state.weather:
            forecast = self._weather_system.get_forecast(self._state.weather, 5)
            rainy_laps = [w for w in forecast if w.condition in ("DRIZZLE", "LIGHT_RAIN", "HEAVY_RAIN")]
            if rainy_laps and self._state.weather.condition == "DRY":
                first_rain_lap = self._current_lap + forecast.index(rainy_laps[0]) + 1
                messages.append(StrategyMessage(
                    msg_type="INFO",
                    text=f"INFO: Rain expected in ~{first_rain_lap - self._current_lap} laps — monitor conditions",
                    confidence=len(rainy_laps) / len(forecast),
                    trigger_lap=self._current_lap,
                ))

        # 3. Undercut threat from car behind
        gap_behind = None
        cars_behind = [c for c in self._cars if c.position == car.position + 1 and c.alive]
        if cars_behind:
            behind = cars_behind[0]
            # Player's gap_to_leader minus behind's gap_to_leader = gap between them
            if car.gap_to_leader is not None and behind.gap_to_leader is not None:
                gap_behind = behind.gap_to_leader - car.gap_to_leader
            elif car.total_time and behind.total_time:
                gap_behind = abs(car.total_time - behind.total_time)

            if gap_behind is not None and gap_behind < 1.0:
                behind_tire_age = behind.tire.age if behind.tire else 0
                if behind_tire_age < car.tire.age - 3:
                    messages.append(StrategyMessage(
                        msg_type="URGENT",
                        text=f"URGENT: Undercut threat from P{car.position + 1} ({behind.driver.name}) on fresher tires",
                        confidence=0.85,
                        trigger_lap=self._current_lap,
                    ))

        # 4. Safety car opportunity
        if self._state.flag == FlagState.SAFETY_CAR:
            messages.append(StrategyMessage(
                msg_type="OPPORTUNITY",
                text="OPPORTUNITY: Safety Car deployed — pit now for free position gain",
                confidence=0.90,
                trigger_lap=self._current_lap,
            ))
        elif self._state.flag == FlagState.VSC:
            messages.append(StrategyMessage(
                msg_type="OPPORTUNITY",
                text="OPPORTUNITY: Virtual Safety Car — consider pit stop",
                confidence=0.75,
                trigger_lap=self._current_lap,
            ))

        # 5. Fuel warning
        expected_fuel_needed = self.track.fuel_per_lap * (self.track.laps - self._current_lap)
        if car.fuel < expected_fuel_needed + 2.0:
            messages.append(StrategyMessage(
                msg_type="WARNING",
                text=f"WARNING: Fuel low — {car.fuel:.1f}kg remaining, ~{expected_fuel_needed:.1f}kg needed",
                confidence=0.95,
                trigger_lap=self._current_lap,
            ))

        # 6. Tire crossover advice (wet weather)
        if self._state.weather:
            crossover = self._weather_system.tire_crossover_point(self._state.weather)
            current_compound = car.tire.compound

            if crossover == "INTERMEDIATE" and current_compound in ("SOFT", "MEDIUM", "HARD"):
                messages.append(StrategyMessage(
                    msg_type="URGENT",
                    text="URGENT: Track conditions require INTERMEDIATE tires — pit immediately",
                    confidence=0.90,
                    trigger_lap=self._current_lap,
                ))
            elif crossover == "WET" and current_compound != "WET":
                messages.append(StrategyMessage(
                    msg_type="URGENT",
                    text="URGENT: Heavy rain — switch to WET tires now",
                    confidence=0.95,
                    trigger_lap=self._current_lap,
                ))
            elif crossover == "SLICK" and current_compound in ("INTERMEDIATE", "WET"):
                messages.append(StrategyMessage(
                    msg_type="OPPORTUNITY",
                    text="OPPORTUNITY: Track drying — ready for SLICK tires",
                    confidence=0.75,
                    trigger_lap=self._current_lap,
                ))

        # Keep only the most recent 10 messages and add new ones
        self._state.messages = self._state.messages[-5:] + messages

    def _finish_race(self) -> None:
        """
        Mark the race as finished and set final positions.

        All alive cars are marked as finished, and the final leaderboard
        is sorted by total race time.
        """
        self._race_finished = True
        self._state.status = "FINISHED"

        for car in self._cars:
            if car.alive:
                car.finished = True

        # Final sort by total time
        self._cars.sort(key=lambda c: c.total_time if c.alive else float('inf'))
        for i, car in enumerate(self._cars, 1):
            car.position = i

        # Add finish message
        winner = self._cars[0]
        self._state.messages.append(StrategyMessage(
            msg_type="INFO",
            text=f"Race finished! Winner: {winner.driver.name} ({winner.driver.team})",
            confidence=1.0,
            trigger_lap=self._current_lap,
        ))

        self._state.leaderboard = list(self._cars)
        self._state.player = self._player_car

    def _tire_failure_probability(self, compound: str, tire_age: int) -> float:
        """Probability of tire failure per lap beyond the predicted life."""
        from .physics import STINT_LIMITS
        limit = STINT_LIMITS.get(compound, 30)
        if tire_age <= limit:
            return 0.0
        excess = (tire_age - limit) / max(limit, 1)
        # Roughly 1.5% at the limit, ~30% at 2× the limit
        return min(0.35, 0.015 * (3.0 ** (excess * 4.0)))

    def _handle_tire_failure(self, car: "CarState") -> None:
        """Apply tire failure consequence (blowout or slow puncture)."""
        is_blowout = self._rng.random() < 0.20
        if is_blowout:
            car.alive = False
            description = f"{car.driver.name} — tire blowout! Car stopped on track."
            severity = "critical"
        else:
            penalty = self._rng.uniform(8.0, 15.0)
            car.total_time += penalty
            description = f"{car.driver.name} — slow puncture, {penalty:.1f}s time loss."
            severity = "major"

        incident = {
            "event_type": "incident",
            "lap": self._current_lap,
            "data": {
                "driver": car.driver.name,
                "driver_number": car.driver.number,
                "severity": severity,
                "description": description,
                "requires_sc": is_blowout,
                "sector": self._rng.randint(1, 3),
                "processed": False,
            },
        }
        self._state.incidents.append(incident["data"])
        self._state.events_log.append(incident)

        msg_type = "URGENT" if is_blowout else "WARNING"
        self._state.messages.append(StrategyMessage(
            msg_type=msg_type, text=description,
            confidence=1.0, trigger_lap=self._current_lap,
        ))

    def _check_track_limits(self, car: "CarState") -> bool:
        """Return True if the car exceeded track limits this lap."""
        # Street circuits (walls) have very low violation tendency
        is_street = any(k in self.track.name.lower()
                        for k in ("monaco", "baku", "marina", "jeddah"))
        base_prob = 0.005 if is_street else min(0.08, 0.008 + self.track.corners * 0.003)

        aggression_mod = (car.driver.aggression - 0.50) * 0.06
        # Increase while in close battle
        battle_mod = 0.02 if (car.gap_to_next is not None and car.gap_to_next < 1.5) else 0.0

        return self._rng.random() < (base_prob + aggression_mod + battle_mod)

    def _check_contact(self, attacker: "CarState", defender: "CarState") -> None:
        """Assess whether a tight overtake attempt caused contact / a penalty."""
        agg = attacker.driver.aggression
        contact_prob = 0.03 + (agg - 0.50) * 0.08  # 3–11%
        if self._rng.random() > contact_prob:
            return

        is_racing_incident = self._rng.random() < 0.40

        if is_racing_incident:
            description = (
                f"Racing incident: {attacker.driver.name} and "
                f"{defender.driver.name} make contact — no penalty"
            )
            penalty_driver_number = None
        else:
            # Driver more likely at fault if higher aggression
            fault_prob = min(0.90, 0.50 + (agg - 0.70) * 1.5)
            at_fault = attacker if self._rng.random() < fault_prob else defender
            other = defender if at_fault is attacker else attacker
            at_fault.total_time += 5.0
            at_fault.contact_penalties += 1
            description = (
                f"{at_fault.driver.name} penalised 5s for collision with "
                f"{other.driver.name}"
            )
            penalty_driver_number = at_fault.driver.number

        event = {
            "event_type": "contact",
            "lap": self._current_lap,
            "data": {
                "attacker": attacker.driver.name,
                "defender": defender.driver.name,
                "description": description,
                "penalty_driver_number": penalty_driver_number,
            },
        }
        self._state.events_log.append(event)

        # Notify player if involved
        is_player_involved = (
            attacker.driver.team == self.player_team
            or defender.driver.team == self.player_team
        )
        if is_player_involved:
            self._state.messages.append(StrategyMessage(
                msg_type="URGENT" if penalty_driver_number else "WARNING",
                text=description, confidence=0.95,
                trigger_lap=self._current_lap,
            ))

    def _ai_pit(self, driver_number: int, compound: str) -> None:
        """
        Execute a pit stop for an AI car (internal method).

        Args:
            driver_number: Racing number of the AI driver.
            compound: Tire compound to fit.
        """
        for car in self._cars:
            if car.driver.number == driver_number and car.alive:
                pit_time = self.track.pit_loss_time
                car.total_time += pit_time
                car.tire = TireState(compound=compound, age=0, wear=0.0)
                car.pits += 1
                break

    def get_final_results(self) -> List[Dict[str, Any]]:
        """
        Get the final race results.

        Returns:
            List of result dictionaries with position, driver, team, total time, etc.
        """
        results = []
        for car in self._cars:
            results.append({
                "position": car.position,
                "driver": car.driver.name,
                "team": car.driver.team,
                "number": car.driver.number,
                "total_time": round(car.total_time, 3),
                "pits": car.pits,
                "status": "FINISHED" if car.alive else "DNF",
                "best_lap": round(car.lap_time, 3) if car.lap_time else None,
            })
        return results

    def get_weather_forecast(self, laps_ahead: int = 10) -> List[Dict[str, Any]]:
        """
        Get a weather forecast for upcoming laps.

        Args:
            laps_ahead: Number of laps to forecast.

        Returns:
            List of forecast dicts with condition, temperature, rain probability.
        """
        if self._state.weather is None:
            return []

        forecast = self._weather_system.get_forecast(self._state.weather, laps_ahead)
        return [
            {
                "lap": self._current_lap + i + 1,
                "condition": f.condition,
                "air_temp": f.air_temp,
                "rain_intensity": f.rain_intensity,
                "track_dampness": f.track_dampness,
                 }
            for i, f in enumerate(forecast)
        ]
